spring:
  application:
    name: media-manager
  # configure multipart file uploads
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
server:
  port: 5100

app:
  base-url: "https://media.regentautovaluers.com"
